services:
  - type: web
    name: NiigataSkiStatus
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app" --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase: false
        value: ${DATABASE_URL}

  - type: cron
    name: update-weather
    schedule: "0 * * * *"
    command: python update_weather.py

databases:
  - name: weather-db
    plan: free